DROP TABLE IF EXISTS en_snapsects;#|#CREATE TABLE `en_snapsects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `status` int(11) DEFAULT NULL,
  `userid` int(11) DEFAULT NULL,
  `author` text,
  `email` text,
  `url` text,
  `colaborative` text,
  `commonname` text,
  `scientificname` text,
  `kingdom` text,
  `phylum` text,
  `classe` text,
  `oorder` text,
  `family` text,
  `genus` text,
  `species` text,
  `gender` text,
  `colors` text,
  `bbody` text,
  `hhead` text,
  `thorax` text,
  `abdomen` text,
  `lstantennae` text,
  `antennae` text,
  `eyesandocelli` text,
  `lstmouthparts` text,
  `mouthparts` text,
  `lstwings` text,
  `wings` text,
  `lstnumlegs` text,
  `lsthindwings` text,
  `hindwings` text,
  `lstlegs` text,
  `cerci` text,
  `tarsomere` text,
  `locomotive` text,
  `specificcharacteristics` text,
  `development` text,
  `metamorphosis` text,
  `collecting` text,
  `place` text,
  `water` text,
  `ground` text,
  `other` text,
  `mediation` text,
  `notes` text,
  `audiodesc` text,
  `datacad` text,
  `lat` text,
  `lng` text,
  `city` text,
  `country` text,
  `uf` text,
  `address` text,
  `photo` text,
  `photodesc` text,
  `win` text,
  `temperature` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;#|#INSERT INTO en_snapsects VALUES("1","0","13","","","","","Athomic Ant","Athomic Ant","Kinder ovo","","16","","Dezenhos animados","","","103","","","","","","","","","","","","","","","","","","","","","110","","","","","","Hanna Barbera 1970","","","","2018-11-08 20:34:51","","","","","","","data:image/jpeg;base64,","","","");#|#


